// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: anemometre

#include "LVGL_UI/ui.h"
#include <stdio.h> //for basic printf commands
#include "esp_log.h" //for showing logs

static void update_spinbox_val(int32_t valeur);

float vent_direction = 0.0f;
//static int32_t valeur_old = 0;  // Garder en mémoire la dernière valeur

////// PILOTE ////////
#include <math.h>
#include "I2C_Driver/I2C_Driver.h"
//////////////////////

/////// AMORTI DE LA FLECHE ////////////
static float filtered_angle = 0;
const float alpha2 = 0.15f; // 0 < alpha < 1 (plus petit = plus amorti)
static float current_angle = 0;
////////////////////////////////////////

void ui_modevent_screen_init(void)
{
    ui_modevent = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_modevent, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_modevent, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_modevent, LV_DIR_LEFT);
    ui_object_set_themeable_style_property(ui_modevent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_modevent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fond);
    lv_obj_set_style_bg_img_src(ui_modevent, &ui_img_coque_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_modevent, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_modevent, LV_PART_MAIN | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fond);

    ui_nombateau = lv_label_create(ui_modevent);
    lv_obj_set_width(ui_nombateau, 100);
    lv_obj_set_height(ui_nombateau, 40);
    lv_obj_set_x(ui_nombateau, 1);
    lv_obj_set_y(ui_nombateau, 205);
    lv_obj_set_align(ui_nombateau, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_nombateau, "Bidibul");
    lv_obj_clear_flag(ui_nombateau, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    //lv_obj_set_style_text_color(ui_nombateau, lv_color_hex(0xD0AC26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_nombateau, lv_color_hex(0xbb9a22), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nombateau, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_nombateau, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nombateau, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_nombateau, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nombateau, &ui_font_Mabook, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_affichagevitesse = lv_label_create(ui_modevent);
    lv_obj_set_width(ui_affichagevitesse, 90);
    lv_obj_set_height(ui_affichagevitesse, 43);
    lv_obj_set_x(ui_affichagevitesse, 159);
    lv_obj_set_y(ui_affichagevitesse, 112);
    lv_obj_set_align(ui_affichagevitesse, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_affichagevitesse, "Nds");
    lv_obj_clear_flag(ui_affichagevitesse,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_affichagevitesse, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_affichagevitesse, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_align(ui_affichagevitesse, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_affichagevitesse, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed = lv_label_create(ui_modevent);
    lv_obj_set_width(ui_speed, lv_pct(61));
    lv_obj_set_height(ui_speed, lv_pct(25));
    lv_obj_set_x(ui_speed, 0);
    lv_obj_set_y(ui_speed, 112);
    lv_obj_set_align(ui_speed, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_speed, "N/A");
    lv_obj_add_flag(ui_speed, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_speed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_speed, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_speed, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_letter_space(ui_speed, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_speed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed, &ui_font_Arial, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vmax = lv_label_create(ui_modevent);
    lv_obj_set_width(ui_Vmax, 47);
    lv_obj_set_height(ui_Vmax, 28);
    lv_obj_set_x(ui_Vmax, -155);
    lv_obj_set_y(ui_Vmax, 64);
    lv_obj_set_align(ui_Vmax, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Vmax, "00");
    lv_obj_add_flag(ui_Vmax, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_Vmax, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_Vmax, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_Vmax, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    //lv_obj_set_style_text_letter_space(ui_Vmax, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Vmax, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Vmax, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vmin = lv_label_create(ui_modevent);
    lv_obj_set_width(ui_Vmin, 47);
    lv_obj_set_height(ui_Vmin, 28);
    lv_obj_set_x(ui_Vmin, 155);
    lv_obj_set_y(ui_Vmin, 64);
    lv_obj_set_align(ui_Vmin, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Vmin, "00");
    lv_obj_add_flag(ui_Vmin, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_Vmin, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_Vmin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_Vmin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_align(ui_Vmin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Vmin, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_max = lv_label_create(ui_modevent);
    lv_obj_set_width(ui_max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_max, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_max, -155);
    lv_obj_set_y(ui_max, 38);
    lv_obj_set_align(ui_max, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_max, "Rafale");
    lv_obj_add_flag(ui_max, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_max, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_max, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_max, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_align(ui_max, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_max, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min = lv_label_create(ui_modevent);
    lv_obj_set_width(ui_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min, 155);
    lv_obj_set_y(ui_min, 38);
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_min, "Vmax Jour");
    lv_obj_add_flag(ui_min, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_min, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_min, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_min, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_align(ui_min, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_min, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_affichagevitesse, ui_event_affichagevitesse, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_speed, ui_event_speed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_modevent, ui_event_modevent, LV_EVENT_ALL, NULL);



    uic_modevent = ui_modevent;
    uic_Lux = ui_Luminosite;
    uic_nombateau = ui_nombateau;
    uic_affichagevitesse = ui_affichagevitesse;
    uic_speed = ui_speed;
    uic_Vmax = ui_Vmax;
    uic_Vmin = ui_Vmin;
    uic_max = ui_max;
    uic_min = ui_min;

}


static void set_value(void * indic, int32_t valeur)
    {
        int32_t direction_int = (int32_t)vent_direction;
        valeur = direction_int;            //// 0 = Nord = 360
        if (direction_int <= 90 && direction_int != 0)
            {
                valeur = direction_int + 270;
            }
        else if (direction_int > 90)
            {
                valeur = direction_int - 90;
            }
        else if (direction_int == 0)
            {
                valeur = 270;
            }
        else if (direction_int > 270)
            {
                valeur = direction_int - 270;
            }
        else if (direction_int == 360)
            {
                valeur = 0;
            }
        if (valeur != 0) 
            {   update_spinbox_val(direction_int); // Appel pour changer la valeur de l'affichage
            } 

        // Correction chemin court
        int32_t delta = valeur - ((int32_t)current_angle % 360);
        if (delta > 180) delta -= 360;
        else if (delta < -180) delta += 360;
        current_angle += delta;

        // rotation 1 tour si arrive à la fin de la gauge
        if (current_angle > 360)
        {
            //ESP_LOGI("ANGLE trop élevé", "current_angle = %.2f", current_angle);
            current_angle = current_angle - 360;
            //ESP_LOGI("=>", "current_angle = %.2f", current_angle);
        }
        else if (current_angle < -360)
        {
            //ESP_LOGI("ANGLE trop faible", "current_angle = %.2f", current_angle);
            current_angle = current_angle + 360;
            //ESP_LOGI("=>", "current_angle = %.2f", current_angle);
        }
        // Filtrage
        filtered_angle = alpha2 * current_angle + (1 - alpha2) * filtered_angle;
        
        lv_meter_set_indicator_value(MyGauge, indic, filtered_angle); // Mise à jour de la valeur de l'aiguille
        //valeur_old = valeur;
    }

// Conversion nœuds → Beaufort
int vitesse_to_beaufort(float vent_vitesse_knots) {
                    if (vent_vitesse_knots < 1.0f) return 0;
                    else if (vent_vitesse_knots < 4.0f) return 1;
                    else if (vent_vitesse_knots < 7.0f) return 2;
                    else if (vent_vitesse_knots < 11.0f) return 3;
                    else if (vent_vitesse_knots < 17.0f) return 4;
                    else if (vent_vitesse_knots < 22.0f) return 5;
                    else if (vent_vitesse_knots < 28.0f) return 6;
                    else if (vent_vitesse_knots < 34.0f) return 7;
                    else if (vent_vitesse_knots < 41.0f) return 8;
                    else if (vent_vitesse_knots < 48.0f) return 9;
                    else if (vent_vitesse_knots < 56.0f) return 10;
                    else if (vent_vitesse_knots < 64.0f) return 11;
                    else return 12;
                }

static void update_spinbox_val(int32_t direction_int)
        {
            //////////////// GRADUATION ////////////////////
            if (direction_int > 180 && direction_int < 360)
                {
                    direction_int = 360 - direction_int;
                }
            lv_spinbox_set_value(ui_Angle, direction_int);
            
            /////////////// AFFICHAGE VITESSE //////////////
            char buffer[64];
            snprintf(buffer, sizeof(buffer), "%.1f", vent_vitesse);
            if (etat_unit)
                {
                }
            else
                {int beaufort = vitesse_to_beaufort(vent_vitesse);
                snprintf(buffer, sizeof(buffer), "%d", beaufort);
                //lv_label_set_text_fmt(ui_speed, buffer);
                }
            
            lv_label_set_text_fmt(ui_speed, buffer);
            char buff[64];
            snprintf(buff, sizeof(buff), "%.1f", vent_rafale);
            if (etat_unit)
                {}
            else
                {int beaufort_rafale = vitesse_to_beaufort(vent_rafale);
                snprintf(buff, sizeof(buff), "%d", beaufort_rafale);
                }
            lv_label_set_text_fmt(ui_Vmax, buff);
            char bufff[64];
            snprintf(bufff, sizeof(bufff), "%d", (int)(vent_rafale_jour + 0.5f));
            if (etat_unit)
                {}
            else
                {int beaufort_rafale_jour = vitesse_to_beaufort(vent_rafale_jour);
                snprintf(bufff, sizeof(bufff), "%d", beaufort_rafale_jour);
                }
            lv_label_set_text_fmt(ui_Vmin, bufff);
        }  



void f_gauge ()
    {
        ///////////////////////// FLECHE /////////////////////////////
        // Création de la gauge
        MyGauge = lv_meter_create(ui_modevent);
        lv_obj_center(MyGauge);
        lv_obj_set_size(MyGauge, 490, 490);
        lv_obj_remove_style(MyGauge, NULL, LV_PART_INDICATOR); //enlever point central
        lv_obj_set_style_bg_opa(MyGauge,  LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT); //fond transparent    

        // echelle
        lv_meter_scale_t* scale = lv_meter_add_scale(MyGauge);
        //lv_meter_set_scale_range(MyGauge, scale, 0, 360, 360, -90);
        lv_meter_set_scale_range(MyGauge, scale, -360, 360, 720, -90);
        
        lv_meter_set_scale_ticks(MyGauge, scale, 73, 2, 10, lv_palette_main(LV_PALETTE_GREY));

        //// CURSEURS PRINCIPAUX ////
        //lv_meter_set_scale_major_ticks(MyGauge, scale, 18, 4, 15, lv_color_hex3(0xf80), -45);     /// eloigne l'echelle des angles à l'extérieur de l'écran  
        lv_meter_set_scale_major_ticks(MyGauge, scale, 9, 4, 15, lv_color_hex3(0xf80), -45);
        lv_meter_indicator_t* indic;

        /*Add a color arc to the start*/
        indic = lv_meter_add_arc(MyGauge, scale, 10, lv_palette_main(LV_PALETTE_RED), 10);
        lv_meter_set_indicator_start_value(MyGauge, indic, 360);
        lv_meter_set_indicator_end_value(MyGauge, indic, 35);

        indic = lv_meter_add_arc(MyGauge, scale, 10, lv_palette_main(LV_PALETTE_ORANGE), 10);
        lv_meter_set_indicator_start_value(MyGauge, indic, 35);
        lv_meter_set_indicator_end_value(MyGauge, indic, 55);

        /*Add a red arc to the end*/
        indic = lv_meter_add_arc(MyGauge, scale, 10, lv_palette_main(LV_PALETTE_ORANGE), 10);
        lv_meter_set_indicator_start_value(MyGauge, indic, 305);
        lv_meter_set_indicator_end_value(MyGauge, indic, 325);

        indic = lv_meter_add_arc(MyGauge, scale, 10, lv_palette_main(LV_PALETTE_RED), 10);
        lv_meter_set_indicator_start_value(MyGauge, indic, 325);
        lv_meter_set_indicator_end_value(MyGauge, indic, 360);

        indic = lv_meter_add_needle_img(MyGauge, scale, &ui_img_fleche_png, 42, 0);

        //////////////////// AFFICHE L'ANGLE DU VENT EN CHIFFRES ///////////////////////////
        ui_Angle = lv_spinbox_create(ui_modevent);
        lv_obj_set_width(ui_Angle, 70);
        lv_obj_set_height(ui_Angle, 52);
        lv_obj_set_x(ui_Angle, 0);
        lv_obj_set_y(ui_Angle, -14);
        lv_obj_set_align(ui_Angle, LV_ALIGN_CENTER);
        lv_obj_add_flag(ui_Angle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);
        lv_obj_clear_flag(ui_Angle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);
        lv_spinbox_set_digit_format(ui_Angle, 3, 0);
        lv_spinbox_set_range(ui_Angle, 0, 360);
        lv_spinbox_set_pos(ui_Angle, 0);
        lv_spinbox_set_value(ui_Angle, 0);  // Initialisation au démarrage
        
        ui_object_set_themeable_style_property(ui_Angle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                                       _ui_theme_color_fondspin);
        ui_object_set_themeable_style_property(ui_Angle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                                       _ui_theme_alpha_fondspin);
        ui_object_set_themeable_style_property(ui_Angle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                                       _ui_theme_color_texte);
        ui_object_set_themeable_style_property(ui_Angle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                                       _ui_theme_alpha_texte);
        lv_obj_set_style_text_align(ui_Angle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(ui_Angle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_t *deg_label = lv_label_create(ui_modevent);
        
        lv_label_set_text_fmt(deg_label, "°");
        lv_obj_set_style_text_font(deg_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_align_to(deg_label, ui_Angle, LV_ALIGN_TOP_RIGHT, 8, -5);
        ui_object_set_themeable_style_property(deg_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                                       _ui_theme_color_fondspin);
        ui_object_set_themeable_style_property(deg_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                                      _ui_theme_alpha_fondspin);
        ui_object_set_themeable_style_property(deg_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                                       _ui_theme_color_texte);
        ui_object_set_themeable_style_property(deg_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                                       _ui_theme_alpha_texte);

        // Animation pour la valeur de l'aiguille //
        lv_anim_t a;
        lv_anim_init(&a);
        lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)set_value);
        lv_anim_set_var(&a, indic);  // L'indicateur à animer
        lv_anim_set_values(&a, -7200, 7200);  // Plage de l'animation
        //lv_anim_set_values(&a, 0, 5);  // Plage de l'animation
        lv_anim_set_time(&a, 100);  // Durée de l'animation (500)
        lv_anim_set_path_cb(&a, lv_anim_path_ease_out); // Animation douce à la fin
        lv_anim_set_repeat_delay(&a, 0);
        lv_anim_set_playback_time(&a, 0);
        lv_obj_clear_flag(ui_Angle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);
        lv_obj_add_flag(ui_Angle, LV_OBJ_FLAG_GESTURE_BUBBLE);
        lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
        //lv_anim_set_early_apply(&a, true);
        lv_anim_start(&a); 
    }
