// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: anemometre

#include "LVGL_UI/ui.h"
#include "../components/lvgl__lvgl/lvgl.h"
#include <stdio.h> //for basic printf commands
#include <stddef.h> //for size_t
#include <string.h> //for handling strings
#include "freertos/FreeRTOS.h" //for delay,mutexs,semphrs rtos operations
#include "esp_system.h" //esp_init funtions esp_err_t 
#include "esp_wifi.h" //esp_wifi_init functions and wifi operations
#include "esp_log.h" //for showing logs
#include "esp_event.h" //for wifi event
#include "nvs_flash.h" //non volatile storage
#include "lwip/err.h" //light weight ip packets error handling
#include "lwip/sys.h" //system applications for light weight ip apps
#include "LVGL_UI/ui_events.h"
//#include <time.h> //for time functions
//#include "freertos/task.h" // for vTaskDelay function



void ui_modeconfig_screen_init(void)
{
    ui_modeconfig = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_modeconfig, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_modeconfig, LV_SCROLLBAR_MODE_ON);
    ui_object_set_themeable_style_property(ui_modeconfig, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_modeconfig, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fond);

    ui_Panel2 = lv_obj_create(ui_modeconfig);
    lv_obj_set_width(ui_Panel2, 287);
    lv_obj_set_height(ui_Panel2, 98);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 155);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel2, LV_SCROLLBAR_MODE_OFF);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fond);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_fond);

    ////// attendre 3 secondes //////
    //vTaskDelay(5000 / portTICK_PERIOD_MS);
    /////////////////////////////////
    
    ///// RECUPERER L'IP /////
    //esp_netif_ip_info_t ip_info;
    //esp_netif_t *wifiInterface = esp_netif_get_handle_from_ifkey("WIFI_STA_DEF");
    //esp_netif_get_ip_info(wifiInterface, &ip_info);
    //////////////////////////

    ui_TextArea3 = lv_textarea_create(ui_modeconfig);
    lv_obj_set_width(ui_TextArea3, 135);
    lv_obj_set_height(ui_TextArea3, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_TextArea3, 0);
    lv_obj_set_y(ui_TextArea3, -55);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);

    lv_textarea_set_text(ui_TextArea3, pass);
    //lv_textarea_set_placeholder_text(ui_TextArea3, "Entrez le mdp..");
    lv_textarea_set_one_line(ui_TextArea3, true);
    //lv_obj_add_flag(ui_TextArea3, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    //lv_obj_clear_flag(ui_TextArea3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
    //                  LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TextArea3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_TextArea3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_letter_space(ui_TextArea3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextArea3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextArea3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TextArea3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_typo);
    ui_object_set_themeable_style_property(ui_TextArea3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_typo);
    ui_object_set_themeable_style_property(ui_TextArea3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_TextArea3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_fond);
    lv_obj_set_style_border_width(ui_TextArea3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TextArea3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
   ///////////////////////////


    ui_Label3 = lv_label_create(ui_modeconfig);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -92);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Label3, "Mot de passe wifi");
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_Label3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);

    ui_Label4 = lv_label_create(ui_modeconfig);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -175);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Label4, "SSID");
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_texte);

    ui_TextArea4 = lv_textarea_create(ui_modeconfig);
    lv_obj_set_width(ui_TextArea4, 135);
    lv_obj_set_height(ui_TextArea4, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_x(ui_TextArea4, 0);
    lv_obj_set_y(ui_TextArea4, -137);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea4, ssid);
    lv_textarea_set_one_line(ui_TextArea4, true);
    ui_object_set_themeable_style_property(ui_TextArea4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_TextArea4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_letter_space(ui_TextArea4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextArea4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextArea4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TextArea4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_typo);
    ui_object_set_themeable_style_property(ui_TextArea4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_typo);
    ui_object_set_themeable_style_property(ui_TextArea4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_TextArea4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_fond);
    lv_obj_set_style_border_width(ui_TextArea4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TextArea4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TextArea4, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_typo);
    ui_object_set_themeable_style_property(ui_TextArea4, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_typo);


    ui_ResetButton = lv_btn_create(ui_modeconfig);
    lv_obj_set_width(ui_ResetButton, 62);
    lv_obj_set_height(ui_ResetButton, 55);
    lv_obj_set_x(ui_ResetButton, 112);
    lv_obj_set_y(ui_ResetButton, -136);
    lv_obj_set_align(ui_ResetButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ResetButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ResetButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ResetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_ResetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fond);
    lv_obj_set_style_bg_img_src(ui_ResetButton, &ui_img_1488500524, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_ResetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_ResetButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_fond);
    ui_object_set_themeable_style_property(ui_ResetButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_fond);
    ui_object_set_themeable_style_property(ui_ResetButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_fond);
    ui_object_set_themeable_style_property(ui_ResetButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_OUTLINE_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_ResetButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_OUTLINE_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_blend_mode(ui_ResetButton, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_modeconfig);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 122);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Label5, "Eclairage");
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    LVGL_Backlight_adjustment(LCD_Backlight);
    
    ui_SliderLuminosite1 = lv_slider_create(ui_modeconfig);
    lv_slider_set_value(ui_SliderLuminosite1, 75, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderLuminosite1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderLuminosite1, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderLuminosite1, 200);
    lv_obj_set_height(ui_SliderLuminosite1, 21);
    lv_obj_set_x(ui_SliderLuminosite1, 5);
    lv_obj_set_y(ui_SliderLuminosite1, 151);
    lv_obj_set_align(ui_SliderLuminosite1, LV_ALIGN_CENTER);
    lv_slider_set_range(ui_SliderLuminosite1, 2, Backlight_MAX);
    lv_obj_add_event_cb(ui_SliderLuminosite1, Backlight_adjustment_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_modeconfig, ui_event_modeconfig, LV_EVENT_ALL, NULL);
    uic_modeconfig = ui_modeconfig;
    uic_SliderLuminosite = ui_SliderLuminosite1;
    uic_ResetButton = ui_ResetButton;

    ui_Luminosite = lv_label_create(ui_modeconfig);
    lv_obj_set_width(ui_Luminosite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Luminosite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Luminosite, -20);
    lv_obj_set_y(ui_Luminosite, 192);
    lv_obj_set_align(ui_Luminosite, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Luminosite, "Mode Jour");
    lv_obj_clear_flag(ui_Luminosite, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_Luminosite, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_Luminosite, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);    

    ///////////// BOUTON MODE NUIT ///////////////////////
    ui_Switch1 = lv_switch_create(ui_modeconfig);
    lv_obj_set_width(ui_Switch1, 40);
    lv_obj_set_height(ui_Switch1, 20);
    lv_obj_set_x(ui_Switch1, 62);
    lv_obj_set_y(ui_Switch1, 192);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xE0470D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ResetButton, ui_event_ResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_modeconfig, ui_event_modeconfig, LV_EVENT_ALL, NULL);
    uic_modeconfig = ui_modeconfig;
    uic_SliderLuminosite = ui_SliderLuminosite1;
    uic_ResetButton = ui_ResetButton;
    uic_Lux = ui_Luminosite2;
    
    //ui_baro = lv_label_create(ui_modeconfig);
    //lv_obj_set_width(ui_baro, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_baro, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_baro, 0);
    //lv_obj_set_y(ui_baro, -8);
    //lv_obj_set_align(ui_baro, LV_ALIGN_CENTER);
    //lv_label_set_text_fmt(ui_baro, "Rafraichissement Barometre");
    //lv_obj_clear_flag(ui_baro, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
    //                  LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
    //                  LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    //ui_object_set_themeable_style_property(ui_baro, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
    //                                       _ui_theme_color_texte);
    //ui_object_set_themeable_style_property(ui_baro, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
    //                                       _ui_theme_alpha_texte);
    //lv_obj_set_style_text_align(ui_baro, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_Switch2 = lv_switch_create(ui_modeconfig);
    //lv_obj_set_width(ui_Switch2, 40);
    //lv_obj_set_height(ui_Switch2, 20);
    //lv_obj_set_x(ui_Switch2, 0);
    //lv_obj_set_y(ui_Switch2, 21);
    //lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    //lv_obj_clear_flag(ui_Switch2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
    //                  LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    //lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xE0470D), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);


    //ui_Label12 = lv_label_create(ui_modeconfig);
    //lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Label12, 64);
    //lv_obj_set_y(ui_Label12, 21);
    //lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    //lv_label_set_text_fmt(ui_Label12, "30 min");
    //ui_object_set_themeable_style_property(ui_Label12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
    //                                       _ui_theme_color_texte);
    //ui_object_set_themeable_style_property(ui_Label12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
    //                                       _ui_theme_alpha_texte);
    //lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    //ui_Label14 = lv_label_create(ui_modeconfig);
    //lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Label14, -55);
    //lv_obj_set_y(ui_Label14, 21);
    //lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    //lv_label_set_text_fmt(ui_Label14, "3 h");
    //ui_object_set_themeable_style_property(ui_Label14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
    //                                       _ui_theme_color_texte);
    //ui_object_set_themeable_style_property(ui_Label14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
    //                                       _ui_theme_alpha_texte);
    //lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_modeconfig);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -212);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Label16, "N/A");  ///// Batterie
    ui_object_set_themeable_style_property(ui_Label16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_Label16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ///////////////////////////////////////////////////
    //////////////   Unité vent  /////////////////////

    ui_unit = lv_label_create(ui_modeconfig);
    lv_obj_set_width(ui_unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_unit, 0);
    lv_obj_set_y(ui_unit, 40);
    lv_obj_set_align(ui_unit, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_unit, "Unite Vent");
    lv_obj_clear_flag(ui_unit, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_unit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_unit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_align(ui_unit, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_modeconfig);
    lv_obj_set_width(ui_Switch3, 40);
    lv_obj_set_height(ui_Switch3, 20);
    lv_obj_set_x(ui_Switch3, 0);
    lv_obj_set_y(ui_Switch3, 76);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xE0470D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);


    ui_Label27 = lv_label_create(ui_modeconfig);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -66);
    lv_obj_set_y(ui_Label27, 76);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Label27, "Noeuds");
    ui_object_set_themeable_style_property(ui_Label27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_Label27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_modeconfig);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 98);
    lv_obj_set_y(ui_Label28, 76);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_Label28, "Echelle Beaufort");
    ui_object_set_themeable_style_property(ui_Label28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_texte);
    ui_object_set_themeable_style_property(ui_Label28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_texte);
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

