// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: anemometre

#include "LVGL_UI/ui.h"
//#include "esp_system.h"
#include "QMI8658.h"
#include <stdbool.h>
#include "esp_log.h"

///////////////////// VARIABLES ////////////////////
//static const char *TAG;
static const char *TAG = "barometre";
bool etat_baro = true;
bool etat_unit = true;


// SCREEN: ui_modevent
void ui_modevent_screen_init(void);
void ui_event_modevent(lv_event_t * e);
lv_obj_t * ui_modevent;
lv_obj_t * ui_Luminosite;
lv_obj_t * ui_nombateau;
lv_obj_t * ui_flechevent;
void ui_event_affichagevitesse(lv_event_t * e);
lv_obj_t * ui_affichagevitesse;
void ui_event_speed(lv_event_t * e);
lv_obj_t * ui_speed;
lv_obj_t * ui_Angle;
lv_obj_t * ui_Vmax;
lv_obj_t * ui_Vmin;
lv_obj_t * ui_max;
lv_obj_t * ui_min;
// CUSTOM VARIABLES
lv_obj_t * uic_modevent;
lv_obj_t * uic_Lux;
lv_obj_t * uic_nombateau;
lv_obj_t * uic_flechevent;
lv_obj_t * uic_affichagevitesse;
lv_obj_t * uic_speed;
lv_obj_t * MyGauge;
lv_obj_t * uic_Vmax;
lv_obj_t * uic_Vmin;
lv_obj_t * uic_max;
lv_obj_t * uic_min;


// SCREEN: ui_modetemp
void ui_modetemp_screen_init(void);
void ui_event_modetemp(lv_event_t * e);
lv_obj_t * ui_modetemp;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Arc1;
// CUSTOM VARIABLES
lv_obj_t * uic_modetemp;
void ta_event_cb(lv_event_t * e);
lv_obj_t * ui_Label0;

lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Labelinclino;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label28;

// SCREEN: ui_modeconfig
void ui_modeconfig_screen_init(void);
void ui_event_modeconfig(lv_event_t * e);
lv_obj_t * ui_modeconfig;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_SliderLuminosite1;
lv_obj_t * ui_TextArea3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_TextArea4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
void ui_event_ResetButton(lv_event_t * e);
lv_obj_t * ui_ResetButton;
void ui_event_Switch1(lv_event_t * e);
void ui_event_Switch2(lv_event_t * e);
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Luminosite2;
lv_obj_t * ui_baro;
lv_obj_t * ui_unit;
//lv_obj_t * ui_Switch2;
lv_obj_t * ui_Switch3;

// SCREEN: ui_modebaro
lv_obj_t * ui_modebaro;
lv_obj_t * ui_graphe;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label33;


// CUSTOM VARIABLES
lv_obj_t * uic_modeconfig;
lv_obj_t * uic_SliderLuminosite;
lv_obj_t * uic_ResetButton;
lv_obj_t * uic_Lux;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// FUNCTIONS ////////////////////
void ui_event_modevent(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_THEMENUIT);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_THEMEJOUR);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_modetemp, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_modetemp_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_modebaro, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_modebaro_screen_init);
    }
}

void ui_event_affichagevitesse(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_THEMENUIT);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_THEMEJOUR);
    }
}

void ui_event_speed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_THEMENUIT);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_THEMEJOUR);
    }
}

void ui_event_modetemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_modevent, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_modevent_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_modeconfig, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_modeconfig_screen_init);
    }
}

void ui_event_modeconfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_modetemp, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_modetemp_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_modebaro, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_modebaro_screen_init);
    }
}

// event funtions
void ui_event_modebaro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_modeconfig, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_modeconfig_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_modevent, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_modevent_screen_init);
    }
}


void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_THEMEJOUR);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_THEMENUIT);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        etat_baro = true;
        ESP_LOGI(TAG,"Tendance pression mise à jour toutes les 1h30");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        etat_baro = false;
        ESP_LOGI(TAG,"Tendance pression mise à jour toutes les 1/2h");
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if (event_code != LV_EVENT_VALUE_CHANGED) return;

    // Vérifie que le label existe et est valide
    if (ui_affichagevitesse == NULL || !lv_obj_is_valid(ui_affichagevitesse)) {
        ESP_LOGE(TAG, "❌ ui_affichagevitesse est NULL ou invalide !");
        return;
    }

    if (!lv_obj_has_state(target, LV_STATE_CHECKED)) {
        etat_unit = true;
        ESP_LOGI(TAG,"Unite vent : Noeuds");
        lv_label_set_text_fmt(ui_affichagevitesse, "Nds");
    } else {
        etat_unit = false;
        ESP_LOGI(TAG,"Unite vent : Beaufort");
        lv_label_set_text_fmt(ui_affichagevitesse, "Bft");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_modevent_screen_init();
    ui_modetemp_screen_init();
    ui_modeconfig_screen_init();
    ui_modebaro_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_modevent);
    f_gauge();
    getAccelerometer();
}


