// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: anemometre


#include "../components/lvgl__lvgl/lvgl.h"
#include "LVGL_UI/ui_helpers.h"
#include "LVGL_UI/ui_events.h"
#include "LVGL_UI/ui_theme_manager.h"
#include "LVGL_UI/ui_themes.h"
#include "QMI8658.h"
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_modevent
void ui_modevent_screen_init(void);
void ui_event_modevent(lv_event_t * e);
void event_click_to_change_screen(lv_event_t *e);

extern lv_obj_t * ui_modevent;
extern lv_obj_t * ui_Luminosite;
extern lv_obj_t * ui_nombateau;
extern lv_obj_t * ui_flechevent;
void ui_event_affichagevitesse(lv_event_t * e);
extern lv_obj_t * ui_affichagevitesse;
void ui_event_speed(lv_event_t * e);
extern lv_obj_t * ui_speed;
extern lv_obj_t * MyGauge;
void f_gauge(void);
extern lv_obj_t * ui_Angle;
extern lv_obj_t * image_fleche;
extern lv_obj_t * ui_Vmax;
extern lv_obj_t * ui_Vmin;
extern lv_obj_t * ui_max;
extern lv_obj_t * ui_min;

// CUSTOM VARIABLES
extern lv_obj_t * uic_modevent;
extern lv_obj_t * uic_Lux;
extern lv_obj_t * uic_nombateau;
extern lv_obj_t * uic_flechevent;
extern lv_obj_t * uic_affichagevitesse;
extern lv_obj_t * uic_speed;
extern lv_obj_t * uic_Vmax;
extern lv_obj_t * uic_Vmin;
extern lv_obj_t * uic_max;
extern lv_obj_t * uic_min;

// SCREEN: ui_modetemp
void ui_modetemp_screen_init(void);
void ui_event_modetemp(lv_event_t * e);
extern lv_obj_t * ui_modetemp;

void start_temperature_task();
void init_http_client();
void parse_json_data(const char *json);
void temperature_task(void *pvParameters);
void update_temperature_display();
//void update_pression_display();
void save_data_to_sdcard(float temperature_max, float temperature_min);
void lire_donnees_sdcard(void);
//void start_memory_monitor();
//void start_heap_trace_on_boot();

////////// TEMPERATURE //////////
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern float temperature_actuelle;
extern float temperature_max;
extern float temperature_min;

/////////// INCLINOMETRE ///////////
extern lv_obj_t * ui_Label0;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Labelinclino;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label21;

////////// PRESSION ////////////////////
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;

///////////// GITE /////////////////
extern float gite;
extern int32_t gite_acc;

///////////// VENT /////////////////
extern float vent_vitesse;
extern float vent_rafale;
extern float vent_rafale_jour;
extern float vent_direction;

// CUSTOM VARIABLES
extern lv_obj_t * uic_modetemp;
extern lv_obj_t * scale;

// SD
extern lv_obj_t * ligne;

// SCREEN: ui_modeconfig
void ui_modeconfig_screen_init(void);
void ui_event_modeconfig(lv_event_t * e);
extern lv_obj_t * ui_modeconfig;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_SliderLuminosite1;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
void ui_event_ResetButton(lv_event_t * e);
extern lv_obj_t * ui_ResetButton;
//void ui_event_TextArea3(lv_event_t * e);
//void ui_event_TextArea4(lv_event_t * e);
void ui_event_Switch1(lv_event_t * e);
void ui_event_Switch2(lv_event_t * e);
void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Luminosite2;
extern lv_obj_t * ui_baro;
//extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label16;
extern bool etat_baro;
extern lv_obj_t * ui_unit;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern bool etat_unit;

// CUSTOM VARIABLES
extern lv_obj_t * uic_modeconfig;
extern lv_obj_t * uic_SliderLuminosite;
extern lv_obj_t * uic_ResetButton;
//static lv_obj_t * needle;  // Aiguille représentée par une image

// SCREEN: ui_modebaro
extern void ui_modebaro_screen_init(void);
//extern void ui_modebaro_screen_destroy(void);
extern void ui_event_modebaro(lv_event_t * e);
extern lv_obj_t * ui_modebaro;
extern lv_obj_t * ui_graphe;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
void baro_add_value(float pression);
void update_baro_chart_scale(lv_obj_t *chart);
extern lv_chart_series_t *ui_graphe_series_1;
extern float pression_actuelle;

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_coque_png);    // assets/coque.png
LV_IMG_DECLARE(ui_img_fleche_png);    // assets/fleche.png
LV_IMG_DECLARE(ui_img_1488500524);    // assets/system-reboot-icon.png


// FONTS
LV_FONT_DECLARE(ui_font_Arial);
LV_FONT_DECLARE(ui_font_Mabook);
LV_FONT_DECLARE(ui_font_Arial12);
LV_FONT_DECLARE(fleches);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif



