// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: projet

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ST7701S.h"

extern const char *ssid; // déclaration externe de la constante
extern const char *pass;

///////////////// VARIABLES ////////////////////

void Backlight_adjustment_event_cb(lv_event_t * e);
void LVGL_Backlight_adjustment(uint8_t Backlight);
void wifi_connection(void);
void reboot_action(lv_event_t * e);

////////////////////////////////////////////////

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
