// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: projet

#include "ui.h"

/////////////  CONNECTION WIFI  //////////////


#include <stdio.h> //for basic printf commands
#include <string.h> //for handling strings
#include "freertos/FreeRTOS.h" //for delay,mutexs,semphrs rtos operations
#include "esp_system.h" //esp_init funtions esp_err_t 
#include "freertos/task.h" // for vTaskDelay function
#include "esp_wifi.h" //esp_wifi_init functions and wifi operations
#include "esp_log.h" //for showing logs
#include "esp_event.h" //for wifi event
#include "nvs_flash.h" //non volatile storage
#include "lwip/err.h" //light weight ip packets error handling
#include "lwip/sys.h" //system applications for light weight ip apps
#include <stdio.h>
#include "esp_log.h"

const char *ssid = "ssid_wifi";
const char *pass = "password_wifi";

int retry_num=0;

//const char* url = "http://192.168.2.237/liveData.html";

static void wifi_event_handler(void *event_handler_arg, esp_event_base_t event_base, int32_t event_id,void *event_data)
{
  if(event_id == WIFI_EVENT_STA_START)
  {
    printf("WIFI CONNECTING....\n");
  }
  else if (event_id == WIFI_EVENT_STA_CONNECTED)
  {
    printf("WiFi CONNECTED\n");
  }
  else if (event_id == WIFI_EVENT_STA_DISCONNECTED)
  {
    printf("WiFi lost connection\n");
    if(retry_num<5){esp_wifi_connect();retry_num++;printf("Retrying to Connect...\n");}
  }
  else if (event_id == IP_EVENT_STA_GOT_IP)
  {
    printf("Wifi got IP...\n");
    esp_netif_ip_info_t ip_info;
    esp_netif_t *wifiInterface = esp_netif_get_handle_from_ifkey("WIFI_STA_DEF");
    esp_netif_get_ip_info(wifiInterface, &ip_info);
    printf(LOG_COLOR(LOG_COLOR_BLUE) "IP address: " LOG_COLOR(LOG_COLOR_GREEN) IPSTR "\n", IP2STR(&ip_info.ip));
    printf(LOG_COLOR(LOG_COLOR_BLUE) "netmask: " LOG_COLOR(LOG_COLOR_GREEN) IPSTR "\n", IP2STR(&ip_info.netmask));
    printf(LOG_COLOR(LOG_COLOR_BLUE) "gateway: " LOG_COLOR(LOG_COLOR_GREEN) IPSTR "\n", IP2STR(&ip_info.gw));
  }
}

void wifi_connection()
{
    // Wi-Fi Configuration Phase
    esp_netif_init();
    esp_event_loop_create_default();     // event loop                    s1.2
    wifi_init_config_t wifi_initiation = WIFI_INIT_CONFIG_DEFAULT();
    esp_wifi_init(&wifi_initiation);  

    // Copie propre dans wifi_config_t
    wifi_config_t wifi_configuration = {0};
    strncpy((char *)wifi_configuration.sta.ssid, ssid, sizeof(wifi_configuration.sta.ssid));
    strncpy((char *)wifi_configuration.sta.password, pass, sizeof(wifi_configuration.sta.password));

    // Enregistrement des handlers d'événements
    esp_event_handler_register(WIFI_EVENT, ESP_EVENT_ANY_ID, &wifi_event_handler, NULL);
    esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, &wifi_event_handler, NULL);
        //esp_log_write(ESP_LOG_INFO, "Kconfig", "SSID=%s, PASS=%s", ssid, pass);
    esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_configuration);
    // 3 - Wi-Fi Start Phase
    esp_wifi_start();
    esp_wifi_set_mode(WIFI_MODE_STA);
    // 4- Wi-Fi Connect Phase
    esp_wifi_connect();
    printf( "wifi_init_softap finished. SSID:%s  password:%s",ssid,pass);
    
}

////////////////////  RELOAD WIFI  ////////////////
void reboot_action(lv_event_t * e)
{
  esp_wifi_disconnect();
  esp_wifi_stop();
  ESP_LOGI("WIFI", "✅ Wi-Fi complètement arrêté");
  vTaskDelay(pdMS_TO_TICKS(4000));  // Attendre logs
  ESP_LOGI("WIFI", "✅ Redémarrage Wi-Fi...");
  wifi_connection();
  temperature_max = temperature_actuelle;
  temperature_min = temperature_actuelle;
  lv_label_set_text_fmt(ui_Label25, "Min: N/A");
  lv_obj_invalidate(ui_Label25);
  lv_label_set_text_fmt(ui_Label26, "Max: N/A");
  lv_obj_invalidate(ui_Label26);
}

void ui_event_ResetButton(lv_event_t * e)
{
      // effacer data temperature //
      lv_event_code_t event_code = lv_event_get_code(e);
      if(event_code == LV_EVENT_LONG_PRESSED) {
        const char *TAG = "SDCARD";
        if (remove("/sdcard/data.csv") == 0) {
            ESP_LOGI(TAG, "✅ Fichier data.csv supprimé avec succès !");
        } else {
           ESP_LOGE(TAG, "❌ Impossible de supprimer data.csv !");
        }
      //////////////////////
      reboot_action(e);
      }
}

/////////////////////  BACKLIGHT  /////////////
void LVGL_Backlight_adjustment(uint8_t Backlight) {
  Set_Backlight(Backlight);                                 
}

void Backlight_adjustment_event_cb(lv_event_t * e) {
  uint8_t Backlight = lv_slider_get_value(lv_event_get_target(e));  
  if (Backlight <= Backlight_MAX)  {
    lv_slider_set_value(ui_SliderLuminosite1, Backlight, LV_ANIM_ON); 
    LCD_Backlight = Backlight;
    LVGL_Backlight_adjustment(Backlight);
  }
}



