// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: projet

#include "../components/lvgl__lvgl/lvgl.h"
#include "LVGL_UI/ui_theme_manager.h"

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_FOND 0
#define UI_THEME_COLOR_TEXTE 1
#define UI_THEME_COLOR_TYPO 2
#define UI_THEME_COLOR_FLECHE 3

#define UI_THEME_DEFAULT 0

#define UI_THEME_THEMEJOUR 1

#define UI_THEME_THEMENUIT 2

extern const ui_theme_variable_t _ui_theme_color_fond[3];
extern const ui_theme_variable_t _ui_theme_alpha_fond[3];

extern const ui_theme_variable_t _ui_theme_color_texte[3];
extern const ui_theme_variable_t _ui_theme_alpha_texte[3];

extern const ui_theme_variable_t _ui_theme_color_typo[3];
extern const ui_theme_variable_t _ui_theme_alpha_typo[3];

extern const ui_theme_variable_t _ui_theme_color_fleche[3];
extern const ui_theme_variable_t _ui_theme_alpha_fleche[3];

extern const ui_theme_variable_t _ui_theme_color_fondspin[3];
extern const ui_theme_variable_t _ui_theme_alpha_fondspin[3];

extern const uint32_t * ui_theme_colors[3];
extern const uint8_t * ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
