// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: anemometre

//#include "../components/lvgl__lvgl/lvgl.h"
#include "LVGL_UI/ui.h"

const ui_theme_variable_t _ui_theme_color_fond[3] = {0xE5CCFF, 0xE5CCFF, 0x180030};
const ui_theme_variable_t _ui_theme_alpha_fond[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_texte[3] = {0x000000, 0x000000, 0xD9D9D9};
const ui_theme_variable_t _ui_theme_alpha_texte[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_typo[3] = {0xFFFFFF, 0xFFFFFF, 0x1F1F1F};
const ui_theme_variable_t _ui_theme_alpha_typo[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_fleche[3] = {0xFF0000, 0x0C7402, 0x0C7402};
const ui_theme_variable_t _ui_theme_alpha_fleche[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_fondspin[3] = {0x000000, 0xFFFFFF, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_fondspin[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_THEMEJOUR;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}